# common-workflow.yml

name: Common CI Workflow

on:
  repository_dispatch:
    types: [trigger-common-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your common workflow steps here
      - name: Run a one-line script
        run: echo Hello from Common Workflow!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
